### project configuration

# C++ project
language: cpp

# Use Ubuntu 14.04 (Trusty)
dist: trusty
sudo: required
group: edge

branches:
  only:
    - travis

git:
    submodules: false

before_install:

  # Get version from git tag
  - export TRAVIS_TAG=$(git describe --abbrev=0 --tags)

  # Download Android NDK from Google
  - curl -OL "https://dl.google.com/android/repository/android-ndk-${TRAVIS_ANDROID_NDK_VERSION}-linux-x86_64.zip"
  - unzip -q -o android-ndk-${TRAVIS_ANDROID_NDK_VERSION}-linux-x86_64.zip
  
### build matrix
matrix:
  include:

    ### Boost 1.69.0 - NDK r18b ###
    # arm64-v8a
    - os: linux
      env:
        - TRAVIS_ANDROID_NDK_VERSION=r18b
        - TRAVIS_BOOST_VERSION=1.69.0
        - TRAVIS_ANDROID_ARCH=arm64-v8a
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    # armeabi-v7a
    - os: linux
      env:
        - TRAVIS_ANDROID_NDK_VERSION=r18b
        - TRAVIS_BOOST_VERSION=1.69.0
        - TRAVIS_ANDROID_ARCH=armeabi-v7a
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    # x86
    - os: linux
      env:
        - TRAVIS_ANDROID_NDK_VERSION=r18b
        - TRAVIS_BOOST_VERSION=1.69.0
        - TRAVIS_ANDROID_ARCH=x86
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    # x86_64
    - os: linux
      env:
        - TRAVIS_ANDROID_NDK_VERSION=r18b
        - TRAVIS_BOOST_VERSION=1.69.0
        - TRAVIS_ANDROID_ARCH=x86_64
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    ### Boost 1.69.0 - NDK r18 ###
    # arm64-v8a
    - os: linux
      env:
        - TRAVIS_ANDROID_NDK_VERSION=r18
        - TRAVIS_BOOST_VERSION=1.69.0
        - TRAVIS_ANDROID_ARCH=arm64-v8a
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    # armeabi-v7a
    - os: linux
      env:
        - TRAVIS_ANDROID_NDK_VERSION=r18
        - TRAVIS_BOOST_VERSION=1.69.0
        - TRAVIS_ANDROID_ARCH=armeabi-v7a
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    # x86
    - os: linux
      env:
        - TRAVIS_ANDROID_NDK_VERSION=r18
        - TRAVIS_BOOST_VERSION=1.69.0
        - TRAVIS_ANDROID_ARCH=x86
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    # x86_64
    - os: linux
      env:
        - TRAVIS_ANDROID_NDK_VERSION=r18
        - TRAVIS_BOOST_VERSION=1.69.0
        - TRAVIS_ANDROID_ARCH=x86_64
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    ### Boost 1.69.0 - NDK r17c ###
    # arm64-v8a
    - os: linux
      env:
        - TRAVIS_ANDROID_NDK_VERSION=r17c
        - TRAVIS_BOOST_VERSION=1.69.0
        - TRAVIS_ANDROID_ARCH=arm64-v8a
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    # armeabi-v7a
    - os: linux
      env:
        - TRAVIS_ANDROID_NDK_VERSION=r17c
        - TRAVIS_BOOST_VERSION=1.69.0
        - TRAVIS_ANDROID_ARCH=armeabi-v7a
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    # x86
    - os: linux
      env:
        - TRAVIS_ANDROID_NDK_VERSION=r17c
        - TRAVIS_BOOST_VERSION=1.69.0
        - TRAVIS_ANDROID_ARCH=x86
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    # x86_64
    - os: linux
      env:
        - TRAVIS_ANDROID_NDK_VERSION=r17c
        - TRAVIS_BOOST_VERSION=1.69.0
        - TRAVIS_ANDROID_ARCH=x86_64
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    ### Boost 1.69.0 - NDK r17b ###
    # arm64-v8a
    - os: linux
      env:
        - TRAVIS_ANDROID_NDK_VERSION=r17b
        - TRAVIS_BOOST_VERSION=1.69.0
        - TRAVIS_ANDROID_ARCH=arm64-v8a
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    # armeabi-v7a
    - os: linux
      env:
        - TRAVIS_ANDROID_NDK_VERSION=r17b
        - TRAVIS_BOOST_VERSION=1.69.0
        - TRAVIS_ANDROID_ARCH=armeabi-v7a
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    # x86
    - os: linux
      env:
        - TRAVIS_ANDROID_NDK_VERSION=r17b
        - TRAVIS_BOOST_VERSION=1.69.0
        - TRAVIS_ANDROID_ARCH=x86
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    # x86_64
    - os: linux
      env:
        - TRAVIS_ANDROID_NDK_VERSION=r17b
        - TRAVIS_BOOST_VERSION=1.69.0
        - TRAVIS_ANDROID_ARCH=x86_64
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    ### Boost 1.69.0 - NDK r16b ###
    # arm64-v8a
    - os: linux
      env:
        - TRAVIS_ANDROID_NDK_VERSION=r16b
        - TRAVIS_BOOST_VERSION=1.69.0
        - TRAVIS_ANDROID_ARCH=arm64-v8a
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    # armeabi-v7a
    - os: linux
      env:
        - TRAVIS_ANDROID_NDK_VERSION=r16b
        - TRAVIS_BOOST_VERSION=1.69.0
        - TRAVIS_ANDROID_ARCH=armeabi-v7a
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    # x86
    - os: linux
      env:
        - TRAVIS_ANDROID_NDK_VERSION=r16b
        - TRAVIS_BOOST_VERSION=1.69.0
        - TRAVIS_ANDROID_ARCH=x86
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    # x86_64
    - os: linux
      env:
        - TRAVIS_ANDROID_NDK_VERSION=r16b
        - TRAVIS_BOOST_VERSION=1.69.0
        - TRAVIS_ANDROID_ARCH=x86_64
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    # armeabi
    - os: linux
      env:
        - TRAVIS_ANDROID_NDK_VERSION=r16b
        - TRAVIS_BOOST_VERSION=1.69.0
        - TRAVIS_ANDROID_ARCH=armeabi
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    # mips
    - os: linux
      env:
        - TRAVIS_ANDROID_NDK_VERSION=r16b
        - TRAVIS_BOOST_VERSION=1.69.0
        - TRAVIS_ANDROID_ARCH=mips
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    # mips64
    - os: linux
      env:
        - TRAVIS_ANDROID_NDK_VERSION=r16b
        - TRAVIS_BOOST_VERSION=1.69.0
        - TRAVIS_ANDROID_ARCH=mips64
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

### build script
script:
  # show OS/compiler version
  - uname -a

  # build
  - ./travis-build.sh

  # zip result
  - cd "${TRAVIS_BUILD_DIR}/build"
  - zip -qr "${TRAVIS_BUILD_DIR}/boost-android-${TRAVIS_ANDROID_NDK_VERSION}-${TRAVIS_ANDROID_ARCH}-${TRAVIS_BOOST_VERSION}.zip" include lib
  - cd "${TRAVIS_BUILD_DIR}"

deploy:
  provider: releases
  api_key:
    secure: "HPlnsQBwMLPKeFFytOHsF/kbY7BpBVZQ/t1G2nmVfZJ5CNzTRRERvzIyENLvVJrNjjFCiZPt0HydBQ5LWAG+qxztzjBsnDwNuWZtDQMBfjsN9yWLBGPGa19G8JavgG7YhvnpHfx1RPPI7VYQlHyIl0eo9OE4Z7wvcg94Ik9zNH4EOn99O7DzMw5c/iJ1uVKuXH7DzUiufUtHw1JnwO8bXM5w1C/tgdq8wtwJ1RflOG0GMmwFFR2B5jxTpD0GfktdPmlCQlekd2NV/WklCu718LQk55tvmsZcC90C64sHvjMR8tGJKcSh9pmkqmY5PWdy51JNqAwVg7WdvkDPFLyj2faO8qeTxT0zohsWn/shwi9GNYh9/W97A3Y04+5vBjp+JSf/ZV6ymdWZ6f5h0XfhKZGeA18jt2f7G35mwJl4oT2tQPRSaUxWgYAkqW7kNzyAOaCyGI1pyAuUrGVJHN4Tzwo9r2TCRqOWlgInDOYjIyT/yt21joxyRNGQznkUErlejcG91DcHqEf+yM5ldtZRARowcArb5brN3UPk5UQDqNqGfyveHuyXiqjNk7VWlyx3YuyPs1e/fklWyk8BK+Ncn9t8v9fHIZPMtOaLaOzsLpz7kv/LhxAfz2hJIReU2z6o2cC4+0w3XCIVKfc2YDhhjSGH7ziS4mF/jIdNgvDBsUs="
  file_glob: true
  file: "boost-android-*.zip"
  skip_cleanup: true
  on:
    branch: travis
    tags: true
