name: CI

env:
  BOOST_VERSION: 1.73.0
  BOOST_LIBS: "atomic,chrono,container,context,coroutine,date_time,exception,filesystem,graph,iostreams,log,math,program_options,random,regex,serialization,system,test,thread,timer,type_erasure,wave"
  NDK_VERSION: "r21b"

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Setup Environment Variables
      run: |
        set -x
        cd ${GITHUB_WORKSPACE}
        # Download Android NDK from Google
        curl -sSOL "https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux-x86_64.zip"
        unzip -q -o android-ndk-${NDK_VERSION}-linux-x86_64.zip

        export NDK_ROOT=${GITHUB_WORKSPACE}/android-ndk-${NDK_VERSION}
        echo "::set-env name=NDK_ROOT::$NDK_ROOT"
        
        export NUM_CPU=`python -c 'import multiprocessing as mp; print(mp.cpu_count())'`
        echo "::set-env name=NUM_CPU::$NUM_CPU"
        set
        mkdir -p bins/android-ndk-${NDK_VERSION}
        mkdir -p logs/android-ndk-${NDK_VERSION}
    - name: Print NDK Version info
      run: cat "${NDK_ROOT}/source.properties"
    - name: Build Boost for Android
      run: CXXFLAGS="-std=c++14" ./build-android.sh --boost=${BOOST_VERSION} --with-libraries=${BOOST_LIBS} "${NDK_ROOT}"
    - name: Prepare Binaries
      run: |
        set -x
        mv build/out/* ${GITHUB_WORKSPACE}/bins/android-ndk-${NDK_VERSION}/ || true
        # Get rid of boost include directory cause it takes a long time to pack and upload (~20 min)
        find ${GITHUB_WORKSPACE}/bins/android-ndk-${NDK_VERSION}/ -type d -name "include" -exec rm -rf {} +
        ls -alFR ${GITHUB_WORKSPACE}/bins/android-ndk-${NDK_VERSION}
      if: always()
    - name: Upload Binaries
      uses: actions/upload-artifact@v1
      with:
        name: binaries
        path: ./bins
      if: always()
    - name: Prepare Logs
      run: |
        set -x
        mv logs/*.log ${GITHUB_WORKSPACE}/logs/android-ndk-${NDK_VERSION}/ || true
        ls -alFR ${GITHUB_WORKSPACE}/logs/android-ndk-${NDK_VERSION}
      if: always()
    - name: Upload Logs
      uses: actions/upload-artifact@v1
      with:
        name: logs
        path: ./logs
      if: always()
